pipeline:
  name: mygit
  identifier: mygit
  projectIdentifier: labsproject
  orgIdentifier: abhilabs
  tags: {}
  stages:
    - stage:
        name: dfs
        identifier: dfs
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echi gelp
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
